version: "3"

services:
  guardian-ui:
    container_name: guardian_ui
    image: ${IMAGE_TAG}

    ports:
      - ${API_PORT}:3005

    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000

    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge