version: "3"

services:
  guardian-ui:
    container_name: guardian_ui
    image: ${IMAGE_TAG}
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge